#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Sync sketch-annotate config from src/sketch/*.yaml to frontend, Worker, and Jekyll."""

from __future__ import annotations

import hashlib
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import yaml

from lib.paths import (
    ASSETS_SKETCH,
    DATA_DIR,
    INCLUDES_DIR,
    ROOT,
    SRC_SKETCH,
    WORKER_GENERATED,
)

GENERATED_HEADER = "/* AUTO-GENERATED by scripts/sketch_sync.py — do not edit */\n"


def _load_yaml(path: Path) -> dict:
    with path.open(encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def _js_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def _asset_version(models: dict, prompts: dict) -> str:
    payload = json.dumps({"models": models, "prompts": prompts}, sort_keys=True, ensure_ascii=False)
    digest = hashlib.sha256(payload.encode("utf-8")).hexdigest()[:10]
    return digest


def _normalize_models(raw: dict) -> tuple[str, list[dict]]:
    models = raw.get("models") or []
    default = raw.get("default")
    if not default:
        for item in models:
            if item.get("default"):
                default = item["id"]
                break
    if not default and models:
        default = models[0]["id"]
    return default, models


def _build_edit_prompt(doubao: str) -> str:
    return (
        "【任务】图像编辑：在原图基础上叠加手绘注释，输出编辑后的完整图片。\n"
        "【硬性要求】\n"
        "1. 必须基于我上传的原图修改，保留原图主体、构图、光线与色彩\n"
        "2. 为画面中每个主要元素分别添加有意义的手绘注释（轮廓线 + 短文案 + 少量装饰）\n"
        "3. 不要整图重绘、不要换场景、不要改变原图内容\n\n" + doubao
    )


def write_sketch_models_include(models: list[dict], default_id: str) -> None:
    lines = [
        "<!-- AUTO-GENERATED by scripts/sketch_sync.py — do not edit -->",
        '  <fieldset class="sketch-mode-group">',
        '    <legend class="sketch-mode-legend">生成方式</legend>',
    ]
    for item in models:
        checked = " checked" if item["id"] == default_id else ""
        lines.append('    <label class="sketch-mode-option">')
        lines.append(
            f'      <input type="radio" name="sketch-model" id="{item["html_id"]}" '
            f'value="{item["id"]}"{checked}>'
        )
        lines.append(f'      {item["label"]}')
        lines.append("    </label>")
    lines.append("  </fieldset>")
    path = INCLUDES_DIR / "sketch-models.html"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_sketch_config_js(default_id: str, models: list[dict], prompts: dict, version: str) -> None:
    labels = {item["id"]: item["short_label"] for item in models}
    payload = {
        "version": version,
        "defaultModel": default_id,
        "models": models,
        "modelLabels": labels,
        "clientPromptShort": (prompts.get("client_short") or "").strip(),
    }
    body = (
        GENERATED_HEADER
        + "(function (root) {\n"
        + f"  root.SKETCH_BUILD = {json.dumps(payload, ensure_ascii=False, indent=2)};\n"
        + "})(typeof window !== 'undefined' ? window : globalThis);\n"
    )
    out = ASSETS_SKETCH / "js" / "sketch-config.js"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(body, encoding="utf-8")


def write_worker_generated(default_id: str, models: list[dict], prompts: dict) -> None:
    WORKER_GENERATED.mkdir(parents=True, exist_ok=True)

    model_ids = [item["id"] for item in models]
    models_js = (
        GENERATED_HEADER
        + f"export const DEFAULT_IMAGE_MODEL = {_js_string(default_id)};\n"
        + f"export const ALLOWED_IMAGE_MODELS = new Set({json.dumps(model_ids, ensure_ascii=False)});\n"
    )
    (WORKER_GENERATED / "models.js").write_text(models_js, encoding="utf-8")

    doubao = (prompts.get("doubao_edit") or "").strip()
    recraft = (prompts.get("recraft_edit") or "").strip()
    edit = _build_edit_prompt(doubao)

    prompts_js = (
        GENERATED_HEADER
        + f"export const DOUBAO_EDIT_PROMPT = {_js_string(doubao)};\n\n"
        + "export const SKETCH_PROMPT = DOUBAO_EDIT_PROMPT;\n\n"
        + f"export const RECRAFT_EDIT_PROMPT = {_js_string(recraft)};\n\n"
        + f"export const EDIT_PROMPT = {_js_string(edit)};\n"
    )
    (WORKER_GENERATED / "prompts.js").write_text(prompts_js, encoding="utf-8")


def write_data_version(version: str) -> None:
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    content = f"asset_version: {version!r}\n"
    (DATA_DIR / "sketch_build.yml").write_text(content, encoding="utf-8")


def sync_sketch() -> str:
    models_raw = _load_yaml(SRC_SKETCH / "models.yaml")
    prompts_raw = _load_yaml(SRC_SKETCH / "prompts.yaml")
    default_id, models = _normalize_models(models_raw)
    version = _asset_version(models_raw, prompts_raw)

    write_sketch_models_include(models, default_id)
    write_sketch_config_js(default_id, models, prompts_raw, version)
    write_worker_generated(default_id, models, prompts_raw)
    write_data_version(version)
    return version


def main() -> int:
    if not SRC_SKETCH.exists():
        print(f"Missing {SRC_SKETCH}", file=sys.stderr)
        return 1
    version = sync_sketch()
    print(f"sketch sync OK (asset_version={version})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
